### ISSUE TITLE
Incompatibility with Figura

### ISSUE THREAD

**Issue by Orthestral** [MineLittlePony/HDSkins#40] opened 2021-05-24 18:59 UTC
Having Figura and HDSkins installed at the same time doesn't allow HDSkins to reach the server.

This is the error message shown when simply _opening_ the skin manager screen
![image](https://user-images.githubusercontent.com/76718984/119394628-03383c00-bc98-11eb-9ced-c45530ecb05b.png)

**Comment by Sollace** [comment] 2021-05-24 19:00
Can you please include the client log files and a link to figura?

**Comment by Orthestral** [comment] 2021-05-24 19:03
Sure thing

https://github.com/TheOneTrueZandra/Figura
[2021-05-24-2.log](https://github.com/MineLittlePony/HDSkins/files/6534498/2021-05-24-2.log)

**Comment by Sollace** [comment] 2021-05-24 19:29
This appears to be caused by something Figura is doing that we can't really fix from our end.

They're installing their own certificate to contact servers at https://figuranew.blancworks.org and either they've done something wrong, or they're adding an outdated LetsEncrypt certificate that prevents LetsEncryptCraft from doing its thing.

I suggest taking the issue up with them.

**Comment by TheOneTrueZandra** [comment] 2021-05-24 21:13
(Figura dev here!)

I don't know if the certificate in question is outdated, but it's likely that it just clashes with the existing one.

Neither mod should need to use LetsEncryptCraft anymore, as Minecraft has updated the JRE to a version that should include the LetsEncrypt certificate that is valid by default.

I'm going to attempt to remove the certificate and see if that works on the new JRE included with Minecraft. If not, I'll just add LetsEncryptCraft as a dependency and that should hopefully fix it regardless.

Sorry about this!

**Comment by Sollace** [comment] 2021-05-24 21:30
Great, thanks! @TheOneTrueZandra 

And in 1.17 I don't envision this being a continued issue for either of us.

**Comment by Sollace** [comment] 2021-07-07 08:18
Closing this as it is for an older version. Please make a new issue the problem still occurs in 1.17.

**Closed as completed by Sollace** 2021-07-07 08:18 UTC
Labels: incompatibility
